### ISSUE TITLE
Unsupervised localization

### ISSUE THREAD

**Issue by mprzewie** [daviswer/fewshotlocal#5] opened 2021-06-02 22:07 UTC
Hello! Thank you very much for sharing the code!

My friends and I are trying to reproduce your results, and we did this more-or-less successfully, except with unsupervised localization models, where we reach very poo (about 7%) accuracies.

We assumed unsupervised localization is switched off / on by the `fewshot_local` parameter in the notebooks, but perhaps there are other parameters we should change in case of the unsupervised models?

We'll be very grateful for your reply :)
Best regards!

**Comment by daviswer** [comment] 2021-06-03 21:37
Hi Marcin,

Thanks for catching this and bringing it to my attention. Your understanding is correct, the fewshot_local parameter controls the choice of few-shot or unsupervised localization. The issue is buried in the Evaluate.ipynb notebook code - there's a quirk in how PyTorch handles lists of modules which was giving certain networks the wrong sets of parameters and messing up the evaluation for unsupervised localization models (others are unaffected).  Unclear if this is tied to specific versions of PyTorch or not, but regardless I just pushed a fix which should now ensure the correct behavior in all cases. Evaluating your currently trained models should now produce the correct scores. 

Hope that fixes things, thanks again for catching this.
Best,
Davis

**Closed as completed by daviswer** 2021-06-03 21:37 UTC

**Comment by mprzewie** [comment] 2021-06-05 21:47
Ok, I checked and this seems to have done the trick. Thank you so much! :)
